### ISSUE TITLE
ROS Publisher and Subscriber

### ISSUE THREAD

**Issue by engrjimmy** [ShibataLab/ros_baxter_workshop#2]
Hi,
Greetings! 
Unfortunately, I found a problem with the ROS publisher and subscriber node using python. 
Here my onhand steps are:
1. I created a workspace for catkin_ws    
2. I completed updates and upgrades
3. I successfully installed all ROS packages in catkin_ws 
Then,
I followed all steps by following http://wiki.ros.org/ROS/Tutorials/WritingPublisherSubscriber%28python%29
But after creating, listener.py and talker.py files I could not able to run it using the pip / terminal command.
Please check the attached file. 
![ROS_problem-01-JM](https://user-images.githubusercontent.com/17684326/97042752-51b31a00-1593-11eb-9da8-a711db69a5a3.JPG)
![ROS_problem-1-JM](https://user-images.githubusercontent.com/17684326/97042791-6099cc80-1593-11eb-93a4-80dc5ea67886.JPG)
![ROS_problem-02-JM](https://user-images.githubusercontent.com/17684326/97042814-698a9e00-1593-11eb-9425-26ecb119b551.JPG)
why I found an error and why I can't run as rosrun beginner_tutorials scripts talker.py / rosrun beginner_tutorials scripts listener.py by following it- http://wiki.ros.org/ROS/Tutorials/ExaminingPublisherSubscriber ? 

I am looking forward to getting a solution.  

Thank you in advance. Happy weekend, happy coding! 
Best regards,
- Jimmy

**Comment by ravijo** [comment]
Hello @engrjimmy 

Thank you very much for creating this issue.  The screenshots shared by you are really helpful to understand the problem.

It seems that you need to learn Linux a little bit. Because originally ROS was built for Linux. So it is helpful to first do a quick exercise on common command-line tools for Linux. Please read from [here](http://www.ee.surrey.ac.uk/Teaching/Unix/).

After finishing the above exercise, I want you to read from [here](http://wiki.ros.org/ROS/Tutorials). Understanding the philosophy behind ROS and the structure of a ROS program is essential. In this way, you will be able to understand why ROS commands are always following one concept.

Finally, [on a side note](https://github.com/ShibataLab/ros_baxter_workshop/tree/main/files#note), it is better is to install Ubuntu on a computer directly. VM is slow and should be used only for learning purposes.

Feel free to comment here if you get stuck somewhere.

**Comment by engrjimmy** [comment]
> Hello @engrjimmy
> 
> Thank you very much for creating this issue. The screenshots shared by you are really helpful to understand the problem.
> 
> It seems that you need to learn Linux a little bit. Because originally ROS was built for Linux. So it is helpful to first do a quick exercise on common command-line tools for Linux. Please read from [here](http://www.ee.surrey.ac.uk/Teaching/Unix/).
> 
> After finishing the above exercise, I want you to read from [here](http://wiki.ros.org/ROS/Tutorials). Understanding the philosophy behind ROS and the structure of a ROS program is essential. In this way, you will be able to understand why ROS commands are always following one concept.
> 
> Finally, [on a side note](https://github.com/ShibataLab/ros_baxter_workshop/tree/main/files#note), it is better is to install Ubuntu on a computer directly. VM is slow and should be used only for learning purposes.
> 
> Feel free to comment here if you get stuck somewhere.

Dear @ravijo  San, 
Thank you so much for your kind reply with a sequential thrust to solve this issue. That's nicely explained by you! 
I try to follow it and I will reply to you back if I feel any problem. 
Thank you!

**Comment by ravijo** [comment]
Thanks, @engrjimmy San

I am closing this issue for now. Please feel free to open it if you face problem.
